branch-defaults:
  deployment:
    environment: bol-env
    group_suffix: null
  master:
    environment: null
global:
  application_name: best-of-life
  branch: null
  default_ec2_keyname: venus-key-pair
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
