branch-defaults:
  development:
    environment: GiversApp
  master:
    environment: Givers
    group_suffix: null
environment-defaults:
  Givers:
    branch: null
    repository: null
  GiversApp:
    branch: null
    repository: null
global:
  application_name: GiversApp
  default_ec2_keyname: key-for-eb-ssh
  default_platform: Ruby 2.3 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
